#include <map>
#include <string>

class Solution { // Sep 22, 2026
public:
  char findTheDifference(std::string s, std::string t) {
    // You are given two strings s and t.
    // String t is generated by random shuffling string s and then add one more letter at a random position.
    // Return the letter that was added to t.

    // Example 1:
    // Input: s = "abcd", t = "abcde"
    // Output: "e"
    // Explanation: 'e' is the letter that was added.

    // Example 2:
    // Input: s = "", t = "y"
    // Output: "y"

    std::map<char, int> sMap;
    std::map<char, int> tMap;

    for(char i : s) sMap[i]++;
    for(char i : t) tMap[i]++;

    std::map<char, int>* biggerMap = sMap.size() >= tMap.size() ? &sMap : &tMap;
    std::map<char, int>* smallerMap = sMap.size() >= tMap.size() ? &tMap : &sMap;

    for(std::pair<char, int> i : *biggerMap)
      if((*smallerMap)[i.first] != i.second) return i.first;

    //not super clean, next time see if you can use XOR solution
    //t is always bigger than s so biggerMap smallerMap junk not needed
    //std::pair<char, int> i copies every element. Use const auto& instead (and the map's element type is really std::pair<const char, int>).
    //pass the strings as const std::string& so they aren't copied.
    //'0' is the digit character zero. '\0' is the usual "no result" value, though with valid input you never reach that line

    return '0';
  }
};
